CREATE TABLE IF NOT EXISTS EMPLEADO (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(20) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(20),
    APELLIDO_PATERNO VARCHAR(20) NOT NULL,
    APELLIDO_MATERNO VARCHAR(20) NOT NULL,
    EDAD INT NOT NULL,
    SEXO VARCHAR(10) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    PUESTO VARCHAR(20) NOT NULL
);